server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true

application:
  test: hello