server:
  port: 8080

spring:
  application:
    name: gateway-service

  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    server:
      webflux:
        discovery:
          locator:
            lower-case-service-id: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


