server:
  port: 9002
spring:
  application:
    name: book-service
  cloud:
    config:
      enabled: true
    vault:
      enabled: true
      uri: ${VAULT_URI:http://vault:8200}
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        application-name: ${spring.application.name}
  config:
    import: optional:configserver:http://localhost:8000