spring:
  application:
    name: user-service
  config:
    import:
      - configserver:http://localhost:8000
      - vault://
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://localhost:8200}
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        application-name: user-service
        default-context: user-service
server:
  port: 8082