server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    defaults:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /libromesh/api-docs
  swagger-ui:
    path: /libromesh/swagger-ui.html
    enabled: true
    urls:
      - name: Gateway Service
        url: /libromesh/api-docs
      - name: User Service
        url: /user-service/libromesh/api-docs  # Via service discovery

