server:
  port: 8000

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ouznoreyni/libromesh-config-repo
          clone-on-start: true

