server:
  port: 8000

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ouznoreyni/libromesh-microservices.git
          search-paths: tree/main/config-repo  # Name of your config folder
          clone-on-start: true

